# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Tunç Başar Köse
has_binder: false
has_settings: false
kind: frontend
labextension_name: detect-duplicate-cells
project_short_description: A JupyterLab extension to detect duplicate cells for nbgrader.
python_name: detect_duplicate_cells
repository: https://github.com/AaltoSciComp/detect-duplicate-cells
test: false

